services:
  - type: web
    name: enem-simulado-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/genisson-ifba/enem-backend-integrated
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"